image: docker:24.0.5

services:
  - docker:24.0.5-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

build-backend:
  stage: build
  rules:
    - changes:
        - pern-backend/**/*
  script:
    - echo "Building Docker image from /pern-backend"
    - cd pern-backend

    # Generate unique tag
    - export TAG="${CI_COMMIT_SHORT_SHA}  

    # Build Docker image
    - docker build -t $DOCKERHUB_USERNAME/pern-backend:$TAG .

    # Login using Docker PAT
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

    # Push image
    - docker push $DOCKERHUB_USERNAME/pern-backend:$TAG


