services:
  backend:
    image: marijahmed/blog-backend
    container_name: backendcont
    env_file:
      - ./pern-backend/.env
    networks:
      - blogapp-network

  frontend:
    image: marijahmed/blog-frontend

    container_name: frontendcont
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - blogapp-network
networks:
  blogapp-network:
    external: true
