services:
  backend:
    build: ./pern-backend
    container_name: backendcont
    env_file:
      - ./pern-backend/.env
    networks:
      - blogapp-network

  frontend:
    build:
      context: ./frontend

    container_name: frontendcont
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - blogapp-network
networks:
  blogapp-network:
    external: true
