apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.metadata.namespace }}

spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
